/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Juego.Jugador;
import Juego.LecturaEscritura;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author corte
 */
public class Clasificacion extends javax.swing.JFrame {
    
    DefaultTableModel dtm = new DefaultTableModel();
    LecturaEscritura le ;
    /**
     * Creates new form Clasificacion
     */
    public Clasificacion() throws IOException, FileNotFoundException, ClassNotFoundException {
        le = new LecturaEscritura();
        le.leerDatos();
        initComponents();
        this.setIconImage(new ImageIcon("src/img/icono.png").getImage());
        setModelo();
        setDatos();
    }
    
    private void setModelo(){
        
        String[]cabezera = {"Nombre","DNI","Jugadas","Ganadas","Perdidas","Facil","Media","Dificil","Imposible"};
        
        dtm.setColumnIdentifiers(cabezera);
        TableRowSorter sorter = new TableRowSorter(dtm);
        tbl.setModel(dtm);
        tbl.setRowSorter(sorter);
    }
    
    private void setDatos(){
        Object[] datos = new Object[dtm.getColumnCount()];
        for (Map.Entry<String, Jugador> entry : le.getJugadores().entrySet()){
            datos[0] = entry.getValue().getNombre();
            datos[1] = entry.getValue().getDNI();
            datos[2] = entry.getValue().getPartidasJugadas();
            datos[3] = entry.getValue().getPartidasGanadas();
            datos[4] = entry.getValue().getPartidasPerdidas();
            datos[5] = entry.getValue().getPuntosTotales()[0];
            datos[6] = entry.getValue().getPuntosTotales()[1];
            datos[7] = entry.getValue().getPuntosTotales()[2];
            datos[8] = entry.getValue().getPuntosTotales()[3];
            dtm.addRow(datos);
        }
        tbl.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
