/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Juego.Jugador;
import Juego.LecturaEscritura;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author eloy
 */
public class IniSesion extends javax.swing.JFrame {
    
    private MenuInicio inicio;
    private LecturaEscritura lecEscr;
    /**
     * Creates new form iniSesion
     */
    public IniSesion( MenuInicio inicio) throws IOException, FileNotFoundException, ClassNotFoundException {
        this.inicio = inicio;
        lecEscr = new LecturaEscritura();
        
        initComponents();
        botonesTransparentes();
        
        this.setLocationRelativeTo(this.inicio);
        this.setVisible(true);
        
        this.setIconImage(new ImageIcon("src/img/icono.png").getImage());
        fallo.setIconImage(new ImageIcon("src/img/icono.png").getImage());
        iniS.setIconImage(new ImageIcon("src/img/icono.png").getImage());
        
        ImageIcon dSure = new ImageIcon("src/img/dialogo2.jpg");
        ImageIcon sure = new ImageIcon(dSure.getImage().getScaledInstance(dialogo.getWidth(), dialogo.getHeight(),Image.SCALE_DEFAULT));
        dialogo.setIcon(sure);
        
        ImageIcon is = new ImageIcon("src/img/is.jpg");
        ImageIcon ise = new ImageIcon(is.getImage().getScaledInstance(inise.getWidth(), inise.getHeight(),Image.SCALE_DEFAULT));
        inise.setIcon(ise);
        
        ImageIcon mal = new ImageIcon("src/img/dialogo.jpg");
        ImageIcon Mal = new ImageIcon(mal.getImage().getScaledInstance(fail.getWidth(), fail.getHeight(),Image.SCALE_DEFAULT));
        fail.setIcon(Mal);
        
        lecEscr.leerDatos();
        fallo.setLocationRelativeTo(this);
    }

    public void botonesTransparentes(){
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        
        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        
        aceptar.setOpaque(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setBorderPainted(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniS = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dialogo = new javax.swing.JLabel();
        fallo = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        inise = new javax.swing.JLabel();

        iniS.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        iniS.setMaximumSize(new java.awt.Dimension(490, 193));
        iniS.setMinimumSize(new java.awt.Dimension(490, 193));
        iniS.setPreferredSize(new java.awt.Dimension(490, 193));
        iniS.getContentPane().setLayout(null);
        iniS.getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 30, 400, 40);
        iniS.getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 50, 200, 40);

        jLabel4.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿ESTAS SEGURO?");
        iniS.getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 80, 190, 30);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        iniS.getContentPane().add(jButton2);
        jButton2.setBounds(80, 110, 68, 32);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        iniS.getContentPane().add(jButton3);
        jButton3.setBounds(330, 110, 73, 32);

        dialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dialogo2.jpg"))); // NOI18N
        iniS.getContentPane().add(dialogo);
        dialogo.setBounds(0, 0, 500, 193);

        fallo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        fallo.setMaximumSize(new java.awt.Dimension(490, 193));
        fallo.setMinimumSize(new java.awt.Dimension(490, 193));
        fallo.setPreferredSize(new java.awt.Dimension(490, 193));
        fallo.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("El DNI que ha dado no es valido pruebe con otro");
        fallo.getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 60, 400, 28);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        fallo.getContentPane().add(jButton4);
        jButton4.setBounds(190, 130, 90, 30);

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("O regístrese si aún no lo ha hecho");
        fallo.getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 90, 280, 30);

        fail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dialogo.jpg"))); // NOI18N
        fail.setMaximumSize(new java.awt.Dimension(490, 193));
        fail.setMinimumSize(new java.awt.Dimension(490, 193));
        fallo.getContentPane().add(fail);
        fail.setBounds(0, 0, 490, 193);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(678, 427));
        setMinimumSize(new java.awt.Dimension(678, 427));
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 172, 290, 40);

        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(200, 290, 250, 90);

        inise.setMaximumSize(new java.awt.Dimension(678, 427));
        inise.setMinimumSize(new java.awt.Dimension(678, 427));
        getContentPane().add(inise);
        inise.setBounds(0, 0, 678, 427);

        setBounds(0, 0, 688, 452);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String dni = jTextField1.getText().toUpperCase();
        if (lecEscr.buscarJugador(dni)!= null){
            Jugador j = lecEscr.buscarJugador(dni);
            jLabel3.setForeground(Color.white);
            jLabel3.setFont(new Font("Bauhaus 93", Font.PLAIN, 18));
            jLabel6.setForeground(Color.white);
            jLabel6.setFont(new Font("Bauhaus 93", Font.PLAIN, 18));
            jLabel3.setText("Estas apunto de jugar como: "+ j.getNombre());
            jLabel6.setText("con DNI: "+ j.getDNI());
            iniS.setLocationRelativeTo(this);
            iniS.setVisible(true);
        }
        else fallo.setVisible(true);
        
    }//GEN-LAST:event_aceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String dni = jTextField1.getText().toUpperCase();
        Jugador j = lecEscr.buscarJugador(dni);
        MenuJuego mj = new MenuJuego(j);
        inicio.dispose();
        this.dispose();
        iniS.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        iniS.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fallo.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel dialogo;
    private javax.swing.JLabel fail;
    private javax.swing.JDialog fallo;
    private javax.swing.JDialog iniS;
    private javax.swing.JLabel inise;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
