/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import Juego.Jugador;
import Juego.LecturaEscritura;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
/**
 *
 * @author eloy
 */
public class Registro extends javax.swing.JFrame {

    private LecturaEscritura lecEscr ;
    private MenuInicio inicio;
    /**
     * Creates new form Registro
     */
    public Registro(MenuInicio inicio) throws IOException, FileNotFoundException, ClassNotFoundException {
        this.inicio = inicio;
        lecEscr = new LecturaEscritura();
        
        initComponents();
        botonesTransparentes();
        
        this.setLocationRelativeTo(this.inicio);
        this.setVisible(true);
        this.setIconImage(new ImageIcon("src/img/icono.png").getImage());
        lecEscr.leerDatos();
        jDialog1.setIconImage(new ImageIcon("src/img/icono.png").getImage());
        
        ImageIcon dSure = new ImageIcon("src/img/dialogo2.jpg");
        ImageIcon sure = new ImageIcon(dSure.getImage().getScaledInstance(dialogo.getWidth(), dialogo.getHeight(),Image.SCALE_DEFAULT));
        dialogo.setIcon(sure);
        
        ImageIcon reg = new ImageIcon("src/img/reg.jpg");
        ImageIcon Reg = new ImageIcon(reg.getImage().getScaledInstance(regi.getWidth(), regi.getHeight(),Image.SCALE_DEFAULT));
        regi.setIcon(Reg);
    }
    
    public void botonesTransparentes(){
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        
        aceptar.setOpaque(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setBorderPainted(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dialogo = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        regi = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        jLabel3.setText("NOMBRE");

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setMaximumSize(new java.awt.Dimension(490, 193));
        jDialog1.setMinimumSize(new java.awt.Dimension(490, 193));
        jDialog1.setPreferredSize(new java.awt.Dimension(500, 220));
        jDialog1.setResizable(false);
        jDialog1.getContentPane().setLayout(null);
        jDialog1.getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 20, 400, 37);

        jLabel7.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("¿ESTAS SEGURO?");
        jDialog1.getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 70, 200, 50);
        jDialog1.getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 50, 220, 30);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton2);
        jButton2.setBounds(80, 120, 68, 32);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton3);
        jButton3.setBounds(330, 120, 73, 32);

        dialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dialogo2.jpg"))); // NOI18N
        dialogo.setMaximumSize(new java.awt.Dimension(500, 200));
        dialogo.setMinimumSize(new java.awt.Dimension(490, 193));
        jDialog1.getContentPane().add(dialogo);
        dialogo.setBounds(0, 0, 500, 220);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(246, 249, 251));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(678, 427));
        setMinimumSize(new java.awt.Dimension(678, 427));
        getContentPane().setLayout(null);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(260, 160, 300, 40);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(260, 230, 300, 40);

        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(210, 310, 240, 70);

        regi.setMaximumSize(new java.awt.Dimension(678, 427));
        regi.setMinimumSize(new java.awt.Dimension(678, 427));
        getContentPane().add(regi);
        regi.setBounds(0, 0, 678, 427);
        regi.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String dni = jTextField3.getText().toUpperCase();
        String nombre = jTextField4.getText().toUpperCase();
        lecEscr.añadirJugador(new Jugador(nombre,dni));
        Jugador j = lecEscr.buscarJugador(dni);
        try {
            lecEscr.guardarDatos();
        } catch (IOException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel6.setForeground(Color.white);
        jLabel6.setFont(new Font("Bauhaus 93", Font.PLAIN, 18));
        jLabel2.setForeground(Color.white);
        jLabel2.setFont(new Font("Bauhaus 93", Font.PLAIN, 18));
        jLabel6.setText("Estas apunto de registrarte como: "+ j.getNombre());
        jLabel2.setText(" con DNI: "+j.getDNI());
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setVisible(true);
        
    }//GEN-LAST:event_aceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuJuego mj = new MenuJuego(lecEscr.buscarJugador(jTextField3.getText().toUpperCase()));
        inicio.dispose();
        this.dispose();
        jDialog1.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel dialogo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel regi;
    // End of variables declaration//GEN-END:variables
}
