@startuml
abstract class Personajes.Personaje
abstract class Personajes.Planta
abstract class Personajes.Zombie
annotation java.lang.Override
annotation java.lang.SuppressWarnings
class Excepciones.ExcepcionJuego
class Excepciones.ExcepcionPlanta
class Juego.Juego
class Juego.Jugador
class Juego.LecturaEscritura
class Juego.Partida
class Juego.Tablero
class Personajes.Caracubo
class Personajes.Deportista
class Personajes.Girasol
class Personajes.LanzaGuisantes
class Personajes.Nuez
class Personajes.Petacereza
class Personajes.ZombieComun
class interfaz.Clasificacion
class interfaz.Comandos
class interfaz.Excepciones
class interfaz.IniSesion
class interfaz.JuegoI
class interfaz.MenuInicio
class interfaz.MenuJuego
class interfaz.Registro
class java.awt.Color
class java.awt.Font
class java.awt.Image
class java.io.BufferedWriter
class java.io.File
class java.io.FileInputStream
class java.io.FileNotFoundException
class java.io.FileOutputStream
class java.io.FileWriter
class java.io.IOException
class java.io.ObjectInputStream
class java.io.ObjectOutputStream
class java.util.HashMap
class java.util.Map
class java.util.logging.Level
class java.util.logging.Logger
class javax.swing.ImageIcon
class javax.swing.JDialog
class javax.swing.JFileChooser
class javax.swing.JFrame
class javax.swing.JLabel
class javax.swing.filechooser.FileNameExtensionFilter
class javax.swing.table.DefaultTableModel
class javax.swing.table.TableRowSorter
interface java.io.Serializable
Personajes.Personaje ..> Juego.Juego
Personajes.Personaje --|> java.io.Serializable
Personajes.Planta --|> Personajes.Personaje
Personajes.Planta ..> Excepciones.ExcepcionPlanta
Personajes.Planta ..> Juego.Juego
Personajes.Zombie --|> Personajes.Personaje
Excepciones.ExcepcionJuego ..> Juego.Juego
Excepciones.ExcepcionJuego ..> interfaz.Excepciones
Excepciones.ExcepcionJuego --|> java.io.Serializable
Excepciones.ExcepcionPlanta ..> Personajes.Personaje
Excepciones.ExcepcionPlanta ..> interfaz.Excepciones
Excepciones.ExcepcionPlanta --|> java.io.Serializable
Juego.Juego ..> Personajes.Zombie
Juego.Juego ..> Excepciones.ExcepcionJuego
Juego.Juego ..> Personajes.Caracubo
Juego.Juego ..> Personajes.Deportista
Juego.Juego ..> Personajes.ZombieComun
Juego.Juego ..> interfaz.Comandos
Juego.Juego --|> java.io.Serializable
Juego.Jugador --|> java.io.Serializable
Juego.LecturaEscritura ..> java.io.FileInputStream
Juego.LecturaEscritura ..> java.io.FileNotFoundException
Juego.LecturaEscritura ..> java.io.FileOutputStream
Juego.LecturaEscritura ..> java.io.IOException
Juego.LecturaEscritura ..> java.io.ObjectInputStream
Juego.LecturaEscritura ..> java.io.ObjectOutputStream
Juego.LecturaEscritura ..> java.util.HashMap
Juego.Partida ..> Personajes.Girasol
Juego.Partida ..> Personajes.LanzaGuisantes
Juego.Partida ..> Personajes.Nuez
Juego.Partida ..> Personajes.Petacereza
Juego.Partida --|> java.io.Serializable
Juego.Tablero ..> Personajes.Personaje
Juego.Tablero --|> java.io.Serializable
Personajes.Caracubo --|> Personajes.Zombie
Personajes.Caracubo ..> java.lang.Override
Personajes.Caracubo ..> Juego.Juego
Personajes.Deportista --|> Personajes.Zombie
Personajes.Deportista ..> java.lang.Override
Personajes.Deportista ..> Juego.Juego
Personajes.Girasol --|> Personajes.Planta
Personajes.Girasol ..> java.lang.Override
Personajes.Girasol ..> Juego.Juego
Personajes.LanzaGuisantes --|> Personajes.Planta
Personajes.LanzaGuisantes ..> java.lang.Override
Personajes.LanzaGuisantes ..> Excepciones.ExcepcionPlanta
Personajes.LanzaGuisantes ..> Juego.Juego
Personajes.Nuez --|> Personajes.Planta
Personajes.Nuez ..> java.lang.Override
Personajes.Nuez ..> Excepciones.ExcepcionPlanta
Personajes.Nuez ..> Juego.Juego
Personajes.Petacereza --|> Personajes.Planta
Personajes.Petacereza ..> java.lang.Override
Personajes.Petacereza ..> Excepciones.ExcepcionPlanta
Personajes.Petacereza ..> Juego.Juego
Personajes.ZombieComun --|> Personajes.Zombie
Personajes.ZombieComun ..> java.lang.Override
Personajes.ZombieComun ..> Juego.Juego
interfaz.Clasificacion ..> java.lang.SuppressWarnings
interfaz.Clasificacion ..> Juego.Jugador
interfaz.Clasificacion ..> Juego.LecturaEscritura
interfaz.Clasificacion ..> java.io.FileNotFoundException
interfaz.Clasificacion ..> java.io.IOException
interfaz.Clasificacion ..> java.util.Map
interfaz.Clasificacion ..> javax.swing.ImageIcon
interfaz.Clasificacion --|> javax.swing.JFrame
interfaz.Clasificacion ..> javax.swing.table.DefaultTableModel
interfaz.Clasificacion ..> javax.swing.table.TableRowSorter
interfaz.Comandos ..> Juego.Juego
interfaz.Comandos ..> Juego.Partida
interfaz.Comandos ..> Juego.Tablero
interfaz.Comandos --|> java.io.Serializable
interfaz.Excepciones ..> java.lang.SuppressWarnings
interfaz.Excepciones ..> java.awt.Image
interfaz.Excepciones ..> javax.swing.ImageIcon
interfaz.Excepciones --|> javax.swing.JDialog
interfaz.Excepciones ..> java.io.Serializable
interfaz.IniSesion ..> java.lang.SuppressWarnings
interfaz.IniSesion ..> Juego.Jugador
interfaz.IniSesion ..> Juego.LecturaEscritura
interfaz.IniSesion ..> java.awt.Color
interfaz.IniSesion ..> java.awt.Font
interfaz.IniSesion ..> java.awt.Image
interfaz.IniSesion ..> java.io.FileNotFoundException
interfaz.IniSesion ..> java.io.IOException
interfaz.IniSesion ..> javax.swing.ImageIcon
interfaz.IniSesion --|> javax.swing.JFrame
interfaz.JuegoI ..> java.lang.SuppressWarnings
interfaz.JuegoI ..> Juego.Juego
interfaz.JuegoI ..> Juego.LecturaEscritura
interfaz.JuegoI ..> Juego.Tablero
interfaz.JuegoI ..> java.awt.Image
interfaz.JuegoI ..> java.io.FileNotFoundException
interfaz.JuegoI ..> java.io.IOException
interfaz.JuegoI ..> java.util.logging.Level
interfaz.JuegoI ..> java.util.logging.Logger
interfaz.JuegoI ..> javax.swing.ImageIcon
interfaz.JuegoI --|> javax.swing.JFrame
interfaz.JuegoI ..> javax.swing.JLabel
interfaz.MenuInicio ..> java.lang.SuppressWarnings
interfaz.MenuInicio ..> Juego.LecturaEscritura
interfaz.MenuInicio ..> java.awt.Image
interfaz.MenuInicio ..> java.io.IOException
interfaz.MenuInicio ..> java.util.logging.Level
interfaz.MenuInicio ..> java.util.logging.Logger
interfaz.MenuInicio ..> javax.swing.ImageIcon
interfaz.MenuInicio --|> javax.swing.JFrame
interfaz.MenuJuego ..> java.lang.SuppressWarnings
interfaz.MenuJuego ..> Excepciones.ExcepcionJuego
interfaz.MenuJuego ..> Juego.Juego
interfaz.MenuJuego ..> Juego.Jugador
interfaz.MenuJuego ..> java.awt.Image
interfaz.MenuJuego ..> java.io.BufferedWriter
interfaz.MenuJuego ..> java.io.File
interfaz.MenuJuego ..> java.io.FileWriter
interfaz.MenuJuego ..> java.io.IOException
interfaz.MenuJuego ..> java.util.logging.Level
interfaz.MenuJuego ..> java.util.logging.Logger
interfaz.MenuJuego ..> javax.swing.ImageIcon
interfaz.MenuJuego ..> javax.swing.JFileChooser
interfaz.MenuJuego --|> javax.swing.JFrame
interfaz.MenuJuego ..> javax.swing.filechooser.FileNameExtensionFilter
interfaz.Registro ..> java.lang.SuppressWarnings
interfaz.Registro ..> Juego.Jugador
interfaz.Registro ..> Juego.LecturaEscritura
interfaz.Registro ..> java.awt.Color
interfaz.Registro ..> java.awt.Font
interfaz.Registro ..> java.awt.Image
interfaz.Registro ..> java.io.FileNotFoundException
interfaz.Registro ..> java.io.IOException
interfaz.Registro ..> java.util.logging.Level
interfaz.Registro ..> java.util.logging.Logger
interfaz.Registro ..> javax.swing.ImageIcon
interfaz.Registro --|> javax.swing.JFrame
@enduml